<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

/**
 * Bootstraps Filament Shield roles + a local super-admin user.
 *
 * - super_admin: full access, every permission generated by shield:generate.
 * - editor:      every permission except User and Setting management.
 *
 * Idempotent. Production runs should rely on the same seeder so role
 * baselines stay deterministic across environments. Permission rows are
 * created by `shield:generate`; this seeder only ensures the two named
 * roles exist and their permission sets are kept in sync.
 */
class RolesAndAdminSeeder extends Seeder
{
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $superAdmin = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
        $editor = Role::firstOrCreate(['name' => 'editor', 'guard_name' => 'web']);

        $allPermissions = Permission::query()->pluck('name')->all();
        $superAdmin->syncPermissions($allPermissions);

        $editorPermissions = collect($allPermissions)
            ->reject(fn (string $name) => str_ends_with($name, '_user')
                || str_ends_with($name, '_any_user')
                || str_ends_with($name, '_role')
                || str_ends_with($name, '_any_role')
                || str_ends_with($name, '_setting')
                || str_ends_with($name, '_any_setting'))
            ->values()
            ->all();
        $editor->syncPermissions($editorPermissions);

        if (!app()->environment('production') && !User::where('email', 'admin@destino.local')->exists()) {
            $admin = User::create([
                'name' => 'Local Admin',
                'email' => 'admin@destino.local',
                'password' => Hash::make('password'),
            ]);
            $admin->assignRole('super_admin');
        } elseif ($admin = User::where('email', 'admin@destino.local')->first()) {
            $admin->syncRoles(['super_admin']);
        }
    }
}
